name: venturiautospurghi
description: All rights rightly right

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.3+29

#config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12' to podfile

environment:
  sdk: ">=2.6.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  url_launcher: ^5.7.10
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  font_awesome_flutter: ^8.10.0
  loading: ^1.0.2
  http: any

  google_sign_in: ^4.5.6
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  firebase_storage: ^5.1.0
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.2+1

  intl: ^0.16.1
  flutter_bloc: ^6.1.1
  json_annotation: 3.1.1
  date_utils: ^0.1.0+3
  queries: ^0.1.14
  bubble_tab_indicator: ^0.1.4
  uuid: ^2.2.2
  equatable: ^1.2.5
  file_picker: ^2.1.0
  dio: ^3.0.10
  flutter_downloader: ^1.5.2

  #mobile only
  fluttertoast: ^7.1.5
  path_provider: 1.6.24
  simple_gesture_detector: ^0.1.4
  sms_autofill: ^1.2.6
  #web only
  js: ^0.6.2
  html: ^0.14.0+3
  js_shims: ^1.0.0
  universal_html: ^1.2.3
  datetime_picker_formfield: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/icona-app.png"
  image_path: "assets/logo-venturi.png"
  android: true
  ios: true
  web: true

  # The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
    - assets/logo.png