name: venturiautospurghi
description: All rights rightly right

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.4+35

#config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12' to podfile

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#  url_launcher: ^5.7.10
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.0
  font_awesome_flutter: ^9.0.0-nullsafety
  loading: ^1.0.2
  http: any

  google_sign_in: ^5.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  firebase_storage: ^8.0.1
  firebase_messaging: ^9.0.0
  firebase_core: ^1.0.2
  cloud_functions: ^1.0.3

  intl: 0.17.0
  flutter_bloc: ^7.0.0-nullsafety.5
  json_annotation: ^4.0.0
  queries: ^0.1.14
  bubble_tab_indicator: ^0.1.6
  uuid: ^3.0.1
  equatable: ^2.0.0
  file_picker: ^3.0.0
  flutter_downloader: ^1.6.0-nullsafety.0
  path: ^1.8.0
  google_place: ^0.4.0
  url_strategy: ^0.2.0

  #mobile only
  url_launcher: ^6.0.2
  fluttertoast: ^8.0.3
  path_provider: ^2.0.1
  simple_gesture_detector: ^0.2.0
#  sms_autofill: ^1.3.1
  
  #web only
  js: ^0.6.3
  datetime_picker_formfield: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/icona-app.png"
  image_path: "assets/logo-venturi.png"
  android: true
  ios: true
  web: true

  # The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
    - assets/logo.png
    - assets/emptyEventLogo.png