name: Android Distribute

on: 
  workflow_dispatch:
    inputs:
        tag:
          description: "Version's name"
          require: true
        bodyTag:
           description: "Descrption of tag" 

jobs:
  build:
    name: Create Android APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '15.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: flutter pub get
    #- run: flutter test
    - name: Download Android keystore
      id: android_keystore
      uses: timheuer/base64-to-file@v1.0.3
      with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
    - name: Create key.properties
      run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
    - name: Decode google-services.json
      env:
        FIREBASE_API_ANDROID: ${{ secrets.FIREBASE_API_ANDROID }}
      run: echo $FIREBASE_API_ANDROID > /home/runner/work/Flutter_organizer-app/Flutter_organizer-app/android/app/google-services.json
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147" 
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.16.x'
    - name: Use cmake
      run: cmake --version 
    - name: Set variable NDK  
      run: export ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/21.3.6528147
    - name: Create apk
      run: flutter build apk -v
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: apk-build
        path: build/app/outputs/apk/release
  deploy:
    needs: [build]
    name: Deploy APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: apk-build
    - name: Decode Firebase credentials distributiion
      id: firebase_credentials_distribution
      uses: timheuer/base64-to-file@v1.0.3
      with:
          fileName: firebase_credentials.json
          encodedString: ${{ secrets.FIREBASE_CREDENTIALS_DISTRIBUTE_BASE64 }}  
    - run: less /home/runner/work/Flutter_organizer-app/Flutter_organizer-app/firebase_credentials.json
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ANDROID}}
        serviceCredentialsFile: /home/runner/work/Flutter_organizer-app/Flutter_organizer-app/firebase_credentials.json
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: Dipendenti
        file: /home/runner/work/Flutter_organizer-app/Flutter_organizer-app/apk-build.apk
  version:
    needs: [deploy]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: ${{ github.event.inputs.bodyTag }}
          draft: false
          prerelease: false
